### ISSUE TITLE
forge-adapt keeps model, effort and context when copying, and contributions state a tier

### ISSUE THREAD

**Issue by agigante80** [agigante80/forge-kit#281]
## Summary

This phase decides a tier for every component, and #253 guards the decision inside this repository. Two paths carry components OUT of it or INTO it, and neither knows the keys exist:

- **forge-adapt copies a component into a project** when it cannot register it (a `scope: project` component, a bare-clone install). On `copy`, `adapt/SKILL.md` Step 3 item 2 has the model REWRITE the whole file "for the project profile", for agents, skills and commands alike, and the only line it is told to keep verbatim is the version marker. So an adapted copy may keep a tier, lose it or have it rewritten, and the drift report cannot tell, because it compares version markers only.
- **A contributed component arrives with whatever its source had.** Neither `.github/ISSUE_TEMPLATE/contribution.yml` nor `forge-adapt contributions`, which files through `gh issue create --body` and bypasses the form, asks about a tier. That is how eight agents came to carry `model: opus` (and `health-check` `model: sonnet`): they were forked with it.

**Revised 2026-09-24 after the round-1 gate.** `scripts/forge-adapt-agent-skills.sh --rewrite` already passes every non-`skills:` frontmatter line through byte-identical (line 209), so its test here PINS existing behaviour rather than changing it. The real gap is the prose rewrite in Step 3, and the refresh report, which has no place for a tier.

## Priority

P2. #253 catches a contributed component at build time, so the contribution half is a better error message rather than a missing guard. The adapt half is a real gap: an installed copy is outside every guard here.

## Affected areas

`components`, `tooling`. `forge-kit-adapt`, a new repository script and the contribution template.

## Files to create/modify

- `plugins/forge-kit-adapt/skills/adapt/SKILL.md`:
  - Step 3 item 2's marker bullet (lines 434 to 437) is widened to keep the `model:`, `effort:`, `context:`, `agent:` and `background:` frontmatter lines verbatim as well;
  - `refresh <name>` step 2 (line 617 on) runs the new script and copies its lines into the report verbatim;
  - contributions mode's `--body` list (line 665) gains "tier + reason".
- **Create** `scripts/forge-adapt-tier-diff.sh`: reports tier-key differences between an installed copy and the catalogue copy (below).
- **Create** `scripts/test-forge-adapt-tier-diff.sh`: its contract test, with a step added to `.github/workflows/validate.yml`.
- `scripts/test-forge-adapt-agent-skills.sh`: pinning cases (below).
- `.github/ISSUE_TEMPLATE/contribution.yml`: an optional `input` field `tier`, whose description links `docs/guides/model-tiers.md`. Optional because the `issue template` category has no tier.
- `adapt/SKILL.md`'s marker and the `forge-kit-adapt` semver; `CLAUDE.md` (a shipped-executables bullet for the new script, and the suite counts via `update-suite-counts.py`).

## Implementation details

**Step 3, the exact change.** The marker bullet becomes: "**Preserve the `<!-- <name>-version: N -->` marker and the `model:`, `effort:`, `context:`, `agent:` and `background:` frontmatter lines verbatim.** The marker is what makes the copy detectable next run; the tier lines are decisions forge-kit made, and a project changes them on purpose or not at all. If the template lacks a marker, add one matching the catalogue version." That keeps the rule the bullet already carries and adds the keys.

**Refresh, in a tested script** (the #149 lever). `scripts/forge-adapt-tier-diff.sh <installed> <catalogue>` reads the FRONTMATTER of both files, which exists only when line 1 is exactly `---` and runs to the next `---` (the rule `scripts/guard-lib.sh`'s `component_frontmatter_field` applies, reused by sourcing it; a `---` rule in a body is never frontmatter), and, for each of `model`, `effort`, `context`, `agent`, `background` in that fixed order, prints one line when the values differ:

```
tier: <key> local=<value> forge-kit=<value> (kept)
```

An absent key prints `-` as its value. Equal keys print nothing. It exits 0 whether or not it printed anything, and exits 2 with nothing on stdout when a file is unreadable or has no frontmatter. Refresh step 2 then reads: "Run `forge-adapt-tier-diff.sh` and copy its lines into the report verbatim; a tier difference is adaptation (keep) and never enters the merge." Because the script reads files rather than agents, it covers skills and commands, which `forge-adapt-agent-skills.sh` never sees.

**The key set is #253's, held in one array.** `effort:` is live on agents today; `context:`, `agent:` and `background:` are skill and command keys in the 2.1.281 schema and appear on no installed component. The script reads the five names from a single array at its top, so if #253 or #252 narrows the set, one line changes and the suite's order case follows it.

**Keep by default, report a difference.** A project that deliberately runs a role cheaper keeps its choice and sees the upstream decision on its own line.

**`agent:` with a plugin scope.** No component carries `agent:` today and #279 expects to adopt none. It is preserved and reported here; if #279 does adopt one, rewriting its plugin scope to the bare project name at install is added to `forge-adapt-agent-skills.sh` in that ticket, the way `skills:` is rewritten.

**The size ratchet.** `adapt/SKILL.md` is at 7209 against a 7209 baseline (`scripts/check-component-size.sh:325`). The additions are about 45 words (the widened bullet's key list, the refresh sentence, "tier + reason"). Payment: the marker bullet's explanation compresses from about 45 words to about 25 as written above, and refresh step 2's two-bucket prose loses its restated examples of adaptation (the tier line now carries one of them). If the result still exceeds 7209, the implementer stops and asks the maintainer for a baseline decision, recorded in the guard with its reason; the baseline is never raised on the implementer's own initiative.

**`contribution.yml` carries no `template-version` and no GWT sections, deliberately.** The new field is a plain form field, not a v6 section, and the lockstep guard is unaffected.

## Acceptance criteria

1. `scripts/test-forge-adapt-agent-skills.sh` pins that `--rewrite` leaves `model`, `effort` and `context` byte-identical, with the keys both before and after a block-list `skills:`, with CRLF, and on the refuse path.
2. Step 3's marker bullet keeps the five tier keys verbatim, in the wording above or tighter.
3. `forge-adapt-tier-diff.sh` prints the fixed line per differing key in the fixed order, nothing for equal keys, exits 0, and exits 2 with empty stdout on an unreadable file or a file with no frontmatter; `refresh <name>` copies its lines verbatim and keeps the local value.
4. Contributions mode's issue body includes a tier line with a reason, and `contribution.yml` has the optional `tier` field linking the guide.
5. `adapt/SKILL.md` does not exceed 7209 words, or the maintainer's baseline decision is recorded in the guard.
6. `adapt/SKILL.md`'s marker and the `forge-kit-adapt` semver are bumped; `CLAUDE.md` and the suite counts are updated.

## Personal data handling

N/A: frontmatter handling, a script reading frontmatter, and a form field; no personal data.

## Security considerations

A security role adapted into a project at a lower tier, silently, would weaken its findings with nothing reporting it. Keeping the tier verbatim on copy, and reporting any difference at refresh, closes that.

## Dependencies

Blocked by #253 (the guide the contribution field links to, and the key set). Related to #279, which decides whether any skill or command gains `context:` or `agent:`.

## Test scenarios (Given / When / Then)

**Condition: the install-time rewrite script keeps tier keys**

Positive
- Given: `.claude/agents/demo.md` whose frontmatter has `model: sonnet`, `effort: low` and `context: fork`, placed both before and after a block-list `skills:` naming `forge-kit-governance:ticket-gate-reference`
- When: `scripts/forge-adapt-agent-skills.sh --rewrite .claude/agents/demo.md` runs
- Then: the skills item reads `ticket-gate-reference`, and the `model:`, `effort:` and `context:` lines are byte-identical to the input (CRLF kept where present)

Negative
- Given: the same agent with a multi-line flow list, `skills: [` continued on the next line
- When: `scripts/forge-adapt-agent-skills.sh --rewrite` runs
- Then: it exits 2 printing `unsupported 'skills:' shape`, and the file, tier keys included, is byte-identical to before

**Condition: a copied component keeps its upstream tier**

Positive
- Given: `forge-adapt-install-plan.sh` returns `copy` for `security-auditor` (upstream `model: opus`)
- When: forge-adapt Step 3 writes `.claude/agents/security-auditor.md`
- Then: the written frontmatter carries `model: opus` exactly as upstream

Negative
- Given: a project copy `.claude/agents/code-reviewer.md` with `model: sonnet`, while the catalogue copy has `model: opus`
- When: `refresh code-reviewer` runs
- Then: the report contains the line `tier: model local=sonnet forge-kit=opus (kept)`, the merged file still says `model: sonnet`, and no other difference row mentions `model`

**Condition: the tier-diff script reports only differences**

Positive
- Given: two files whose frontmatter differs only in `effort` (`low` locally, absent in the catalogue)
- When: `scripts/forge-adapt-tier-diff.sh <installed> <catalogue>` runs
- Then: stdout is exactly `tier: effort local=low forge-kit=- (kept)` and it exits 0

Negative
- Given: an installed file with no frontmatter
- When: the script runs on it
- Then: it exits 2, stdout is empty, and stderr names the file

**Condition: a contribution states its tier**

Positive
- Given: a project-only agent `.claude/agents/a11y-reviewer.md` with `model: sonnet`, accepted in `forge-adapt contributions`
- When: the contribution issue is created
- Then: the issue body includes a tier line naming `sonnet` and a reason

Negative
- Given: a project-only agent `.claude/agents/a11y-reviewer.md` with no `model:` line, accepted in `forge-adapt contributions`
- When: the contribution issue is created
- Then: the issue body's tier line reads `inherit` with its reason, never a blank or an invented tier

A contribution whose tier its role's row does not allow is #253's scenario, since #253 ships the check that refuses it.

## Unit tests

- `scripts/test-forge-adapt-agent-skills.sh`: one case per key (`model`, `effort`, `context`) byte-identical after `--rewrite`; the keys before AND after a block-list `skills:` (which pins the `inlist` reset at line 208); a CRLF file; the flow-list refuse path leaving the file unchanged.
- `scripts/test-forge-adapt-tier-diff.sh`: identical frontmatter prints nothing; one line per differing key in the fixed order; an absent key prints `-`; all five keys differing prints five lines in order; a tier key in the BODY (below the second `---`) is ignored; a file whose line 1 is not `---` but which has a body `---` rule followed by `model: opus` is treated as having no frontmatter; no frontmatter exits 2 with empty stdout; an unreadable file exits 2. Mutants: reading the whole file instead of the frontmatter; accepting a first `---` below line 1; dropping the fixed order.

## Required reviews (mandatory)

- [x] **ticket-gate** - mandatory before implementation. Mechanical checks + one critic (plus the security lens by label). Must return PASS.

## QA & Security testing

- [ ] `bash scripts/test-forge-adapt-agent-skills.sh`, `bash scripts/test-forge-adapt-tier-diff.sh`, `bash scripts/check-component-size.sh`
- [ ] One real forge-adapt `copy` install of a tiered agent into a throwaway project, frontmatter inspected afterwards
- [ ] One real `refresh <name>` on that copy after hand-editing its `model:`, report inspected for the tier line

## E2E test scenarios

N/A: a skill, a script and a form field with no application UI. The real install and refresh in QA are the end-to-end surface.

## Documentation impact

- **Docs affected:** `adapt/SKILL.md`, `contribution.yml`, `CLAUDE.md` (a bullet for `forge-adapt-tier-diff.sh` in the shipped-executables list, the validation list, and the suite counts).
- **README impact:** none; the new script is repository tooling for forge-adapt, not a component.
- **Why not, if none:** N/A.

## Codebase Context

`scripts/forge-adapt-agent-skills.sh --rewrite` (line 141 on) edits only `skills:` lines; everything else falls through `{ print $0 cr }` at line 209. `adapt/SKILL.md` Step 3 item 2 is at line 414, its marker bullet at 434 to 437, `refresh <name>` at 611 with the two-bucket classification at 617, and contributions mode's `gh issue create --body` at 664 and 665. `grep -nE 'model|effort'` over `adapt/SKILL.md` and `contribution.yml` finds nothing (2026-09-24). 8 agents declare `model: opus` and `health-check.md:18` declares `model: sonnet`. The skill and command keys `context`, `agent` and `background` are the ones the 2.1.281 binary's frontmatter schema describes (quoted in #279's Codebase Context); #252 re-confirms them against the installed CLI before this ticket's key list ships, and a correction is a one-line change to the array.

### Codebase context (gate, 2026-09-24)
**Relevant files:**
- `scripts/forge-adapt-agent-skills.sh`: `--rewrite` (line 141 on) edits only the `skills:` list; every other frontmatter line falls through a pass-through `print $0 cr`, so `model:`/`effort:`/`context:` already survive byte-identical. AC1 is a pinning test, not a behaviour change.
- `plugins/forge-kit-adapt/skills/adapt/SKILL.md`: Step 3 (line 402) runs `forge-adapt-install-plan.sh`; on `copy`, item 2 (line 414) has the model REWRITE the whole file "for the project profile", and the only line it is told to keep verbatim is the version marker (lines 434 to 437). That LLM rewrite is where a tier is likelier to be lost, and it covers agents, skills and commands alike.
- `plugins/forge-kit-adapt/skills/adapt/SKILL.md`: `refresh <name>` (line 611) sorts every difference into "adaptation (keep)" or "behind forge-kit (offer to apply)", with no tier bucket; the no-argument `drift` report compares markers only, through `scripts/forge-adapt-drift-status.sh` (two version numbers in, one word out, never reads frontmatter).
- `scripts/forge-adapt-install-plan.sh`: reads `scope:`/`scope-reason:` frontmatter only.
- `.github/ISSUE_TEMPLATE/contribution.yml`: fields `category`, `summary`, `rationale`, `source`, `content`, `checklist`; no tier field, no `template-version`. Only `check-template-lockstep.sh` names it, to exempt it.

**Existing tests:**
- `scripts/test-forge-adapt-agent-skills.sh`: 45 passing; `ok`/`bad`/`eq` helpers and an `agent()` heredoc fixture writer. No test covers adapt Step 3's prose or `refresh`.

**Constraints:**
- `adapt/SKILL.md` measures 7209 words against a 7209 ratchet (`check-component-size.sh:325`): zero headroom, so any new prose must be paid for in the same edit.
- No component under `plugins/` carries `effort:`, `context:` or `agent:` frontmatter today; 8 agents carry `model: opus` and `health-check` carries `model: sonnet`.
- `docs/guides/model-tiers.md` does not exist yet (#253, open).

### Gate verdict (round 3)
**Verdict:** PASS
Full review: the latest `## Ticket Readiness Review` comment on this issue.

**Comment by agigante80** [comment]
## Ticket Readiness Review - #281

**Issue:** forge-adapt keeps model, effort and context when copying, and contributions state a tier
**Date:** 2026-09-24
**Round:** 1
**Template version:** v6 (current: v6)
**Review set:** mechanical checks + critic. No lens: labels are `feature`, `P2`, `components`, so neither the security nor the API row triggers. Research (Step 2.7) was not triggered: at most one complexity signal.
**Mechanics:** `plugins/forge-kit-governance/skills/ticket-gate-reference/assets/check-ticket-mechanics.sh` (check-ticket-mechanics-version: 10), run from the forge-kit checkout. Thin-ticket pre-check: 0 material questions.

**Verdict: NEEDS-WORK** - the tests point at the path that already works (the script). The path that actually loses a tier, the model rewriting a copied template in forge-adapt Step 3, has no mechanism, no test and no word budget.

### Mechanical checks
| Check | Result | Evidence |
|---|---|---|
| Template version current | pass | `template-version: 6` |
| Labels valid | pass | `feature,P2,components` (`components` is an area in `docs/guides/labels.md`) |
| Required sections present | pass | every template section present and filled (headings at `##`) |
| GWT structure | referred | the negative Then "reports the tier difference on its own line" is not mechanically specific. The critic judged it: **fail** (below) |
| Test specs concrete | pass | `scripts/test-forge-adapt-agent-skills.sh`, one case per key plus both YAML shapes |
| E2E N/A | referred | the critic judged it: **N/A accepted**. `contribution.yml` is a form GitHub renders, not project UI, and no suite here could drive it |
| Documentation impact present | pass | `adapt/SKILL.md`, `contribution.yml` |

### Critique
- **The gap is not where the tests point.** `scripts/forge-adapt-agent-skills.sh --rewrite` edits only the `skills:` lines. Every other frontmatter line passes through `{ print $0 cr }` (line 209), so `model:`, `effort:` and `context:` already come out byte-identical today. AC1 pins existing behaviour; it changes nothing.
  - The real risk is `adapt/SKILL.md` Step 3 item 2 (line 414): on `copy`, the model rewrites the whole template "for the project profile". That covers agents, skills and commands. The only thing it is told to keep verbatim is the version marker (lines 434 to 437).
  - The script runs later, inside item 4 (lines 440 to 455), so it can only keep what the model already wrote.
  - AC2 names no mechanism and no test for that path, or for the refresh tier line.
- **Refresh has no tier bucket.** `refresh <name>` step 2 (line 617 on) sorts every difference into "adaptation (keep)" or "behind forge-kit (offer to apply)". The ticket's own line format is unspecified, so nothing can test it.
- **Zero headroom.** `adapt/SKILL.md` measures 7209 words against its 7209 ratchet (`scripts/check-component-size.sh:325`). The ticket says the rule goes "in the tested script where it can", but the only script it names handles agents' `skills:` lines. It never runs on skills or commands, and never during refresh. So none of the new rule can live there as scoped, and the ticket does not say where the words come from.
- **The contribution half misses the kit's own filer.** `forge-adapt contributions` creates contribution issues with `gh issue create --body "<category / what it does / ...>"` (`adapt/SKILL.md` lines 664 and 665), which bypasses `contribution.yml` entirely. The ticket's premise is exactly the component that arrives "with whatever its source had", and a form field never reaches this path.
- **Factual error in the Summary.** "nine agents came to carry `model: opus`" is wrong against the tree: 8 agents declare `model: opus`, and `health-check.md:18` declares `model: sonnet`. CLAUDE.md carries the same claim.
- **Key set.** `agent:` is unaddressed. #279 pairs `context: fork` with an `agent:` key, and that value may be plugin-scoped (`plugin:name`). Kept byte-identical in a project copy, a plugin-scoped name fails silently, the #124 class this script exists to prevent for `skills:`. No component carries `effort:`, `context:` or `agent:` today, so this is advisory, but it is cheapest to decide now.
- **Hard bars.** UI E2E (rule 3): N/A accepted, as above. API coverage (rule 2): N/A, no endpoint. Personal data (rule 4): the N/A holds against the file list, which is frontmatter handling and a form field.
- **Documentation (rule 7).** Broadly met. Also name CLAUDE.md: the `scripts/test-forge-adapt-agent-skills.sh` count will change, and it is regenerated with `python3 scripts/update-suite-counts.py` (the pre-push hook checks it). A new script would also need its own bullet in CLAUDE.md's list of shipped executables.
- **Split:** none needed; one area.

### GWT review
- **Condition 1.** The Positive is fine but describes what already happens. The Negative is not Condition 1's negative: it is a different condition (refresh). Its Then names no line format a test could check.
- **Condition 2.** The Positive's When, "it is read", is not an action. A GitHub issue form cannot validate a textarea's content, so the Then cannot be tested as written. The Negative relies on #253's message, which does not exist yet.
- **Missing conditions:** the Step 3 copy path, skills and commands, contributions mode, and the refuse path.

Improved scenarios (the critic's; the refusal text is verified against `forge-adapt-agent-skills.sh:133`):

**Condition: the install-time rewrite script keeps tier keys**

Positive
- Given: `.claude/agents/demo.md` whose frontmatter has `model: sonnet`, `effort: low` and `context: fork`, placed both before and after a block-list `skills:` naming `forge-kit-governance:ticket-gate-reference`
- When: `scripts/forge-adapt-agent-skills.sh --rewrite .claude/agents/demo.md` runs
- Then: the skills item reads `ticket-gate-reference`, and the `model:`, `effort:` and `context:` lines are byte-identical to the input (CRLF kept where present)

Negative
- Given: the same agent with a multi-line flow list, `skills: [` continued on the next line
- When: `scripts/forge-adapt-agent-skills.sh --rewrite` runs
- Then: it exits 2 printing `unsupported 'skills:' shape`, and the file, tier keys included, is byte-identical to before

**Condition: a copied component keeps its upstream tier**

Positive
- Given: `forge-adapt-install-plan.sh` returns `copy` for `security-auditor` (upstream `model: opus`)
- When: forge-adapt Step 3 writes `.claude/agents/security-auditor.md`
- Then: the written frontmatter carries `model: opus` exactly as upstream

Negative
- Given: a project copy `.claude/agents/code-reviewer.md` with `model: sonnet`, while the catalogue copy has `model: opus`
- When: `refresh code-reviewer` runs
- Then: the report contains the line `tier: model local=sonnet forge-kit=opus (kept)`, the merged file still says `model: sonnet`, and no other difference row mentions `model`

**Condition: a contribution states its tier**

Positive
- Given: a project-only agent `.claude/agents/a11y-reviewer.md` with `model: sonnet`, accepted in `forge-adapt contributions`
- When: the contribution issue is created
- Then: the issue body includes a tier line naming `sonnet` and a reason

Negative
- Given: a contribution adding an agent whose tier its role's row in `docs/guides/model-tiers.md` does not allow
- When: #253's check runs in `Validate`
- Then: the build fails with #253's message naming the allowed set for that role (exact pattern pinned when #253 lands)

### Pros and cons
- **Pros:** "keep by default, report the difference" is right: it respects a deliberate project choice without hiding the upstream decision, and it closes the silent security-downgrade case the ticket names. AC1 is cheap regression cover for a shared parser. Leaving `contribution.yml`'s marker-free design alone is correct.
- **Cons:** as written, every test can go green while the gap stays open. With zero ratchet headroom and no named payment, AC4 forces either an unplanned baseline request or a rule squeezed too tight to follow. The form field misses the kit's own contribution filer.

### Best practices
Skipped, with a reason. The one open external question is whether skills and commands honour `model:`, `effort:` and `context: fork`. #252's probe owns that, and #253 (this ticket's blocker) records the installed CLI (2.1.281) as accepting them. Searching again here would duplicate that work.

### Suggested approach
1. **Step 3.** Widen the marker-preserve bullet (line 434) so it also keeps the `model:`, `effort:` and `context:` frontmatter lines verbatim. Pay for the words by tightening that bullet's own explanation, or ask the maintainer.
2. **Refresh, in a tested script** (the #149 lever). Add either a `--tier` mode on `forge-adapt-agent-skills.sh` or a new `scripts/forge-adapt-tier-diff.sh <installed> <catalogue>`. It prints one fixed line per differing key, `tier: <key> local=<v> forge-kit=<v> (kept)`, and exits 0. Refresh step 2 runs it and copies its lines into the report verbatim, so the prose shrinks to one line naming the script. That also covers skills and commands, which the rewrite script never sees.
3. **Contributions mode.** Add "tier + reason" to the `--body` list at line 665.
4. **Form.** Add an optional `input` field `tier` to `contribution.yml`, with a description linking `docs/guides/model-tiers.md`. Optional, because the `issue template` category has no tier.
5. **`agent:`.** Decide it: rewrite a plugin-scoped value the way `skills:` is rewritten, or refuse it.
6. **Tests.** One case per key; keys both before and after a block list, which pins the `inlist` reset at line 208; CRLF; the refuse path; and a contract suite for the tier-diff script.

### Advisory (non-blocking)
- Correct "nine agents carry `model: opus`" in the Summary and in CLAUDE.md: 8 opus plus `health-check` on sonnet.
- Decide the `agent:` key now (Suggested approach 5).
- Add the extra unit edge cases in Suggested approach 6.
- Docs impact: add CLAUDE.md (regenerate the suite count with `python3 scripts/update-suite-counts.py`; add a shipped-executable bullet if a new script lands).
- The contribution negative scenario depends on #253's message; pin it once #253 lands.
- Ordering: AC1, AC2 and the contributions-mode change do not depend on #253; only the guide link does. They can start before #253 closes.

### Required changes (when NEEDS-WORK)

- [ ] significant: Specify the mechanism and tests for the path that actually loses a tier. `adapt/SKILL.md` Step 3 item 2 (line 414) has the model rewrite agents, skills and commands, and keeps only the version marker verbatim (lines 434 to 437). Add (1) the exact Step 3 wording change keeping `model:`/`effort:`/`context:`; (2) a tested script for the refresh tier difference, with its fixed output line and contract cases; (3) since `adapt` is at 7209/7209 (`check-component-size.sh:325`), where the words are paid from, or an explicit maintainer ask.
- [ ] significant: Rewrite the GWT to rule 1. Condition 1's Negative is a different condition with a non-specific Then; Condition 2's Positive has no real When and cannot be tested. Adopt the improved scenarios above: script keeps keys, refuse path, Step 3 copy keeps tier, refresh prints the fixed tier line, contributions-mode body.
- [ ] significant: Cover forge-adapt contributions mode, which files through `gh issue create --body` (`adapt/SKILL.md` lines 664 and 665) and bypasses `contribution.yml`. Add "tier + reason" to that body list in Files to modify and the ACs, or state why it is out of scope.

**Comment by agigante80** [comment]
## Ticket Readiness Review - #281

**Issue:** forge-adapt keeps model, effort and context when copying, and contributions state a tier
**Date:** 2026-09-24
**Round:** 2
**Template version:** v6 (current: v6)
**Review set:** mechanical checks + critic (no lens: no `security`/`critical` label; no `api` or `privacy` label)
**Mechanics:** `plugins/forge-kit-governance/skills/ticket-gate-reference/assets/check-ticket-mechanics.sh` (check-ticket-mechanics-version: 10)
**Round scope:** the three round-1 blocking items plus the sections revised in response (Summary's revision note, Files, Implementation details, Acceptance criteria, Test scenarios, Unit tests, QA). Carried forward unchanged: Priority, Affected areas, Personal data, Security, Dependencies, Documentation impact. Codebase context reused from round 1 (no fundamental item then). Research re-run: none, because the revision introduces no new technology, dependency or regulation.

**Verdict: NEEDS-WORK** - all three round-1 items are resolved, but the rewritten Condition 4 Negative tests #253's unshipped check, and its Then says the exact message is "pinned when #253 lands", so it is not a specific outcome of this ticket.

### Mechanical checks
| Check | Result | Evidence |
|---|---|---|
| Template version current | pass | `template-version: 6` |
| Labels valid | pass | `feature,P2,components` |
| Required sections present | pass | every template section present and filled (headings at `##`) |
| GWT structure | referred | a negative Then is not mechanically specific (Condition 2's refresh Then); the critic ruled it specific, see below |
| Test specs concrete | pass | `scripts/test-forge-adapt-agent-skills.sh` cases per key |
| E2E specs | referred | N/A claimed; the critic ruled it legitimate, see below |
| Documentation impact present | pass | `adapt/SKILL.md`, `contribution.yml`, `CLAUDE.md` |

### Critique
**Round-1 items**
1. **Mechanism, tests and budget for the Step 3 rewrite and the refresh tier line: resolved.** The ticket now gives the exact bullet wording, the `forge-adapt-tier-diff.sh` contract (fixed line, fixed key order, exit 0 and exit 2), its test cases with two named mutants, and a word-budget plan with an explicit maintainer-ask fallback (AC5). That fallback is exactly what the round-1 change asked for.
2. **GWT to rule 1: resolved for the two problems named.** Condition 1's Negative is now the same condition's failure path. Its message matches the script's real stderr (`unsupported 'skills:' shape`, `scripts/forge-adapt-agent-skills.sh:133`). Condition 2's Positive now has a real When, and because Step 3 is an LLM rewrite it is routed to QA's real install rather than claimed as a unit test. That is the correct placement.
3. **Contributions mode: resolved.** The `--body` list change (`adapt/SKILL.md:665`), AC4 and the optional `tier` field on `contribution.yml` are all specified.

**Mechanical referrals**
- *GWT specificity (Condition 2 Negative):* specific. The Then asserts an exact report line, the merged file's `model: sonnet`, and no other row naming `model`. Rule 1 requires a specific outcome, and that is broader than the heuristic's error-message test.
- *E2E N/A:* legitimate. Rule 3 concerns the project's own application screens, and forge-kit ships none. A GitHub-hosted issue form is not an application UI this repo builds or tests end to end, and QA's real install and refresh are the stated end-to-end surface.

**New in this round's delta**
- **Condition 4 Negative (blocking, significant).** "When #253's check runs in `Validate` / Then the build fails with #253's message ... (exact pattern pinned when #253 lands)". `docs/guides/model-tiers.md` does not exist (verified), the check belongs to #253, and this ticket is blocked by #253. The scenario describes behaviour #281 does not implement, and its Then defers its own assertion. That fails rule 1's "a SPECIFIC error code or message" on inspection.

**Always-on bars:** rule 2 N/A (no endpoint). Rule 3 as above. Rule 4 N/A accepted: the file list is frontmatter handling, a frontmatter reader and a form field. Rule 7: the Documentation impact names every surface the file list touches.

### GWT review
Conditions 1 to 3 meet the rule-1 bar: each scenario has one When and a specific Then, checked against real script output where that can be checked. Condition 4's Positive stands. Its Negative should be replaced with one inside this ticket's own scope, for example:

```
Negative
- Given: a project-only agent `.claude/agents/a11y-reviewer.md` with no `model:` line, accepted in `forge-adapt contributions`
- When: the contribution issue is created
- Then: the body's tier line reads `inherit` with its reason, and no tier the file does not declare is named
```

Alternatively, drop the disallowed-tier case and state in one line that it is #253's scenario, pinned in #253's ticket. Either resolves the item.

### Pros and cons
**Pros:** the round-1 fixes are substantive. The diff script turns a prose judgement into a tested contract (the #149 lever). Keep-and-report respects a project's deliberate choice while still surfacing upstream decisions. And the unit/QA split is honest about what a bash suite can and cannot assert.
**Cons:** the GWT rewrite fixed two named problems and introduced a third in the same pass. The word-budget arithmetic is optimistic. And the five-key list includes one key with no precedent found (advisory below).

### Best practices
Skipped: routine repository tooling. The new script follows the existing `scripts/forge-adapt-*.sh` convention (`catalogue`, `install-plan`, `drift-status`, `neighbour-disposition`), each called from `adapt/SKILL.md` through `$FORGE_KIT_DIR/scripts/` and each run as its own `validate.yml` step. Key usage was checked against the installed marketplaces in this run: `^effort:` appears in 8 files, `^context:` in 1, `^agent:` in 1, and `^background:` in none.

### Suggested approach
Replace Condition 4's Negative only, as above, and re-run the gate. Leave everything else untouched so the round-3 target does not grow.

**Advisory (non-blocking):**
- The ratchet payment ("marker bullet compresses from about 45 words to about 25") does not hold when the proposed wording is counted, because the bold lead gains five key names. AC5's maintainer-ask fallback covers this, so plan on using it.
- Of the five keys, `effort:` is confirmed on real agent frontmatter. `context:` and `agent:` appear only as skill-level execution keys. `background:` was found as frontmatter nowhere in the installed marketplaces. A wrong key is harmless (absent on both sides prints nothing), but confirm the set against #253 before the fixed order ships as a tested contract.

### Required changes (when NEEDS-WORK)
- [ ] Replace Condition 4's Negative scenario, which runs #253's unshipped `Validate` check and defers its Then ("exact pattern pinned when #253 lands"), with a Negative inside #281's own scope (e.g. a contribution with no `model:` line whose tier line reads `inherit` with its reason). Or remove it with a one-line statement that the disallowed-tier case is #253's scenario.

**Comment by agigante80** [comment]
## Ticket Readiness Review - #281

**Issue:** forge-adapt keeps model, effort and context when copying, and contributions state a tier
**Date:** 2026-09-24
**Round:** 3
**Template version:** v6 (current: v6)
**Review set:** mechanical checks + critic (no lens: no `security`/`critical` label; no `api` or `privacy` label)
**Mechanics:** `plugins/forge-kit-governance/skills/ticket-gate-reference/assets/check-ticket-mechanics.sh` (check-ticket-mechanics-version: 10)
**Round scope:** the round-2 blocking item (Condition 4's Negative) plus the text changed in response (Condition 4 and its scope-out sentence, and the Implementation details paragraph on the key set). Carried forward unchanged from round 2: every other section. Codebase context reused (round 2 had no fundamental item). Research: none re-run, because the delta introduces no new technology, dependency or regulation.

**Verdict: PASS** - the one round-2 blocking item is resolved exactly as suggested, and none of the changed text breaks a rule.

### Mechanical checks
| Check | Result | Evidence |
|---|---|---|
| Template version current | pass | `template-version: 6` |
| Labels valid | pass | `feature,P2,components` |
| Required sections present | pass | every template section present and filled (headings at `##`) |
| GWT structure | referred | Condition 2's refresh Then is not mechanically specific; the critic rules it specific (see below) |
| Test specs concrete | pass | `scripts/test-forge-adapt-agent-skills.sh` cases per key |
| E2E specs | referred | N/A with a reason; the critic rules it legitimate (see below) |
| Documentation impact present | pass | `adapt/SKILL.md`, `contribution.yml`, `CLAUDE.md` |

### Critique
**Round-2 item: resolved.** Condition 4's Negative no longer runs #253's unshipped check. It now covers a contributed agent with no `model:` line, and its Then asserts that the tier line reads `inherit` with its reason, never blank or invented. That is one When, stated declaratively, with a specific and checkable Then inside #281's own scope. The line that follows it, "A contribution whose tier its role's row does not allow is #253's scenario", is the one-line scope-out round 2 offered as the alternative, and it is prose rather than a scenario.

**Changed text: the key-set paragraph.** Verified in this run: `scripts/guard-lib.sh` defines `component_frontmatter_field` (line 67), so reusing it by sourcing is accurate. The installed CLI reports `2.1.281`. The claim that `context:`, `agent:` and `background:` are skill and command keys in that schema could not be confirmed from the installed binary, so it is advisory only. The ticket is blocked by #253 (still open) and holds the set in one array, so a correction is a one-line change.

**Mechanical referrals:** both flag text round 2 already ruled on, and that text is unchanged. The Condition 2 Then names an exact report line (`tier: model local=sonnet forge-kit=opus (kept)`), which is a specific outcome. The E2E N/A holds because forge-kit ships no application UI, and QA's real install and refresh cover the end-to-end surface.

**Always-on bars:** rule 2 N/A (no endpoint). Rule 3 as above. Rule 4 N/A accepted (frontmatter handling and a form field). Rule 7: carried forward as complete.

### GWT review
Condition 4 now meets the rule-1 bar. Conditions 1 to 3 are unchanged since round 2, which ruled them sound. No scenarios were written by the gate this round.

### Pros and cons
**Pros:** the fix is minimal and on target, staying inside #281's scope, and the scope-out sentence names the disallowed-tier case without testing code that does not exist yet.
**Cons:** the "2.1.281 schema" attribution is stated more confidently than can be verified locally. This is mitigated by the dependency on #253.

### Best practices
Skipped: a routine scenario fix that raises no new external-practice question.

### Suggested approach
Implement as written once #253 lands. Revisit the five-key array only if #253 narrows or reorders the set.

**Advisory (non-blocking):**
- Reconfirm that `context:`, `agent:` and `background:` are real skill or command frontmatter keys (against #253 or the Claude Code docs) before the fixed key order ships as a tested contract.
- Round 2's advisory on the word-budget arithmetic still applies: plan on AC5's maintainer-ask fallback.

### Required changes (when NEEDS-WORK)

**Comment by agigante80** [comment]
Shipped in af4f215 (Validate green on develop and main). adapt Step 3 keeps model, effort, context, agent and background verbatim beside the marker; `refresh <name>` runs the new `scripts/forge-adapt-tier-diff.sh` (23 tests, 3 mutants) and reports each tier difference as kept; contributions and contribution.yml ask for tier and reason. The agent-skills suite now pins that `--rewrite` leaves tier lines byte-identical (54 tests). adapt shrank 7209 to 7206, baseline lowered. Review: round 1 (code-reviewer) found no high or medium; its three lows are filed as a follow-up ticket.
